<?php 

class Config {
    static $_strAlien = '../aliencode'; // where is the alienframework?
    static $_fDebug = true;
    //static $_fLogDirectOutput = true; // print all log into the output stream
    static $_fLogInfoSytemErrorDirectOutput = true; // print system errors into the output stream
    //static $_fInfoDirectOutput = true; // print system errors into the output stream
    static $_strDebugLog = '/var/log/alien/example01-log-02-database.log';
    //static $_strGeneratedDbClassesPath = ''; // classes generated by the table defenitions
    static $_strAbsPath; // WILL BE SET IN init()!!    

    static $_DB_DB='alien';
    static $_DB_HOST='localhost';
    // static $_DB_PORT='14000'; optional
    static $_DB_USER='alien';
    static $_DB_PWD='alien';
    static $_DB_PREFIX = 'alien_';
    


    static $_DB_DEBUG_TABLE = 'debug_log2';

    static function init() {
        self::$_strAbsPath = dirname( __FILE__ );
        if ( ! is_dir( '/var/log/alien' ) ) { // are we on a local test system, then use different values.
            static $_DB_PREFIX = 'alien_';            
            self::$_strDebugLog = '../../logs/example01-log-02-database.log';
        }        
    }
}

Config::init();